# Generated by Django 4.2.7 on 2025-06-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_card_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
