services:
  - type: web
    name: django-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn shared_expenses_system.wsgi.application
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-subdomain.onrender.com
