# Generated by Django 4.2.7 on 2025-06-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='merchant_account_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
